accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import signup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
)


urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from projects.views import ProjectRedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("", ProjectRedirectView.as_view(pattern_name="home")),
    path("", RedirectView.as_view(), name="home"),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(
        User,
        related_name="projects",
    )

    def __str__(self):
        return f"{self.name}"

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(default=timezone.now)
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return f"{self.name}"

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

projects/views.py
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
from projects.models import Project
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectRedirectView(RedirectView):
    url = "/projects/"
    pattern_name = "home"
    success_url = reverse_lazy("home")

    def get_sucess_url(self):
        return reverse_lazy("home", args=[self.object.id])


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]
    success_url = reverse_lazy("home")

    def get_sucess_url(self):
        return reverse_lazy("home", args=[self.object.id])

tasks/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from tasks.models import Task
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]
    success_url = reverse_lazy("home")

    def get_sucess_url(self):
        return reverse_lazy("home", args=[self.object.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "tasks/update.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

    def get_sucess_url(self):
        return reverse_lazy("show_my_tasks", args=[self.object.id])

projects/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Project Alpha</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url "logout" %}">Logout</a></li>
          <li><a href="{% url "show_my_tasks" %}">My Tasks</a></li>
          <li><a href="{% url "list_projects" %}">My Projects</a></li>
          {% endif %} 
          {% if user.is_anonymous %}
          <li><a href="{% url "signup" %}">Sign Up</a></li>
          <li><a href="{% url "login" %}">Login</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>{% block content %} {% endblock content %}</main>
  </body>
</html>

projects/templates/projects/create.html
{% extends "base.html" %} 
{% block content %}
            <div>
                <h1>Create a new project</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                        <button class="button">Create
                        </button>
                </form>
            </div>
{% endblock content %}

projects/templates/projects/detail.html
{% extends "base.html" %}
{% load markdownify %}
{% block content %}

    <main>
        <div>
            <h1>{{ project.name }}</h1>
            {{ project.description|markdownify }}
            <h2>Tasks</h2>
            <p>
                <a href="{% url "create_task" %}">Create a new task</a>
            </p>
            {% if project.tasks.all|length > 0 %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in project.tasks.all %}
                    
                    <tr>
                        <td>{{ task.name }}</td>
                        <td>{{ task.assignee }}</td>
                        <td>{{ task.start_date }}</td>
                        <td>{{ task.due_date }}</td>
                        <td>{{ task.is_completed|yesno }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p>This project has no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <title>Projects</title>
    </head>
    <body>
        <main>
            <div>
                <h1>My Projects</h1>
                <p>
                    <a href="{% url 'create_project' %}">
                        Create a new project
                    </a>
                </p>
                {% if project_list|length > 0 %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for project in project_list %}
                        <tr>
                            <td><a href="{% url "show_project" project.id %}"></a>
                                {{ project.name }}
                            </td>
                            <td>{{ project.tasks.all | length }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p>You are not assigned to any projects</p>
                {% endif %}
            </div>
        </main>
    </body>
</html>

tasks/templates/tasks/create.html
{% extends "base.html" %} 
{% block content %}
            <div>
                <h1>Create a new task</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                        <button class="button">Create
                        </button>
                </form>
            </div>
{% endblock content %}

tasks/templates/tasks/list.html
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        <main>
            <div>
                <h1>My Tasks</h1>
                {% if task_list|length == 0 %}
                <p>You have no tasks</p>
                {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for task in task_list %}
                        <tr>
                            <td>{{ task.name }}</td>
                            <td>{{ task.start_date }}</td>
                            <td>{{ task.end_date }}</td>
                            {% if task.is_completed == True %}
                            <td>Done</td>
               
                            {% else %}
                            <td><form method="post" action="{% url 'complete_task' task.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="is_completed" value="True">
                                <button>Complete</button></form>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div>
        </main>
    </body>
</html>